export const actionTypes = {
    ADD_TO_COMPARE: "ADD_TO_COMPARE",
    LOAD_COMPARE_ISSUE:"LOAD_COMPARE_ISSUE",
    SELECT_ISSUE_VALUE:"SELECT_ISSUE_VALUE",
    REMOVE_FROM_COMPARE:"REMOVE_FROM_COMPARE"
}