export const actionTypes = {
    ADD_TO_COMPARE: "ADD_TO_COMPARE",
    LOAD_COMPARE_ISSUES:"LOAD_COMPARE_ISSUES",
    LOAD_COMPARE_POLITICIANS:"LOAD_COMPARE_POLITICIANS",
    SELECT_ISSUE_VALUE:"SELECT_ISSUE_VALUE",
    REMOVE_FROM_COMPARE:"REMOVE_FROM_COMPARE",
    SET_COMPARE_VALUE:"SET_COMPARE_VALUE"
}